apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-tasks.fullname" . }}-secret
  labels:
    {{- include "home-tasks.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ .Values.secrets.secretKey | default "change-me-in-production" | quote }}
